jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "This is a build step"
  tfsec:
    machine: true
    steps:
      - checkout

      - run: docker run --rm -v $(pwd):/src aquasec/tfsec /src -f json | tee tfsec-output.json

      - store_artifacts:
          path: tfsec-output.json
          destination: tfsec-artifact

  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"

  integration:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    machine: true
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - tfsec
      - test
          requires:
            - tfsec
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
